export const ENDPOINTS = {
  globalSearch: "/search/",
  configuration: "/configuration",
  popularMovies: "/movie/popular",
  popularTvShows: "/tv/popular",
  popularPeople: "/person/popular",
  movieById: "/movie/",
  showById: "/tv/",
  trendingToday: "/trending/all/day",
  trendingMoviesToday: "/trending/movie/day",
  trendingShowsToday: "/trending/tv/day",
  trendingPeopleToday: "/trending/person/day",
  movieGenres: "/genre/movie/list",
  tvGenres: "/genre/tv/list",
  discover: "/discover/",
};
